-- 1
SELECT TABLESPACE_NAME, CONTENTS, STATUS FROM DBA_TABLESPACES;

-- 2
SELECT FILE_NAME, TABLESPACE_NAME, STATUS FROM DBA_DATA_FILES
UNION ALL
SELECT FILE_NAME, TABLESPACE_NAME, STATUS FROM DBA_TEMP_FILES;

-- 3 группа журналов повтора
SELECT GROUP#, THREAD#, SEQUENCE#, ARCHIVED, STATUS FROM V$LOG;

-- 4 файлы-журналы
SELECT GROUP#, MEMBER FROM V$LOGFILE;

-- 5
SELECT CURRENT_SCN FROM V$DATABASE;
ALTER SYSTEM SWITCH LOGFILE;
SELECT CURRENT_SCN FROM V$DATABASE;

-- 6 доп группа журналов повтора
ALTER DATABASE ADD LOGFILE GROUP 3
    ('/opt/oracle/oradata/FREE/redo03a.log',
    '/opt/oracle/oradata/FREE/redo03b.log',
    '/opt/oracle/oradata/FREE/redo03c.log') SIZE 20M;
SELECT GROUP#, THREAD#, SEQUENCE#, ARCHIVED, STATUS FROM V$LOG;
ALTER SYSTEM SWITCH LOGFILE;
SELECT CURRENT_SCN FROM V$DATABASE;

-- 7
SELECT GROUP#, THREAD#, SEQUENCE#, ARCHIVED, STATUS FROM V$LOG;
ALTER SYSTEM CHECKPOINT;
ALTER DATABASE DROP LOGFILE GROUP 3;

-- 8 режима архивирования
SELECT LOG_MODE FROM V$DATABASE;

-- 9 номер последнего архива
SELECT MAX(SEQUENCE#) FROM V$ARCHIVED_LOG;

-- 10 включить архивирование в sqlplus
/*
SHUTDOWN IMMEDIATE;
STARTUP MOUNT;
ALTER DATABASE ARCHIVELOG;
ALTER DATABASE OPEN;
*/

-- 11
ALTER SYSTEM ARCHIVE LOG CURRENT;
SELECT MAX(SEQUENCE#) FROM V$ARCHIVED_LOG;
SELECT * FROM V$ARCHIVED_LOG ORDER BY SEQUENCE# DESC;

SELECT LOG_MODE FROM V$DATABASE;

-- 12 отключить архивирование
/*
SHUTDOWN IMMEDIATE;
STARTUP MOUNT;
ALTER DATABASE NOARCHIVELOG;
ALTER DATABASE OPEN;
*/
SELECT LOG_MODE FROM V$DATABASE;


-- 13
SHOW PARAMETER control_files;

select * from v$controlfile_record_section

ALTER DATABASE BACKUP CONTROLFILE TO TRACE;
ALTER DATABASE BACKUP CONTROLFILE TO '/opt/oracle/oradata/FREE/tracee.trc';

select * from v$diag_info

create pfile = 'p1.ora' from spfile;